### ISSUE TITLE
Bug in Token verification

### ISSUE THREAD

**Issue by lukasbisdorf** [larsonnn/strapio#7]
I maybe came across some issues with the checking of a token: 

Is it intended, that a connection can be established even if no token is provided (no query object at all)? 
To go even further: If a user connects without a token, he will receive ALL events without permission checking... 

If a user connects to the socket with an invalid token, it causes an exception in strapi, but the user did not get any feedback over the socket, that maybe the token is invalid.

Could you verify that there may is a bug in this package?

**Comment by x0ptr** [comment]
When handshake is not valid strapio will not disconnect the connection to the socket client.

Thanks for seeing this!

Please install / update `2.4.5`

fixed by https://github.com/larsonnn/strapio/commit/d3285f30389f6c89aa94abe533db838c55edb96c
